#! /bin/bash

if [[ -z $1 ]]
then
  echo "Please specify release version" 1>&2
  exit 1
fi

APP_VERSION=$1
TMP_DIR="./target/pack"
TMP_DOC_DIR="$TMP_DIR/doc"

# Compile and pack the application
sbt clean pack

# Prepare documentation directory and content
mkdir -v $TMP_DOC_DIR
cp -rv images $TMP_DOC_DIR/
pandoc --from markdown_github --to html5 --standalone -o "$TMP_DOC_DIR/README.html" README.md
pandoc --from markdown_github --to html5 --standalone -o "$TMP_DOC_DIR/RELEASENOTES.html" RELEASENOTES.md
echo $APP_VERSION > "$TMP_DOC_DIR/VERSION.txt"

# Remove not needed stuff generated by sbt-pack
rm -v "$TMP_DIR/Makefile"
rm -v "$TMP_DIR/VERSION"

# Create distribution archive
tar -cvzf target/dbstress-$APP_VERSION.tgz -C target/ --transform s/pack/dbstress-$APP_VERSION/ pack/

